# Makefile 

FIGURE = example.mp

### Build instructions

datahandling: 
	mpost datahandling

modelsfig: 
	mpost models 

algorithm: 
	mpost EMalg 

all:
	mpost datahandling
	mpost models
	pdflatex notes.tex

latex:
	pdflatex notes.tex
