# Makefile 

FIGURE = example.mp

### Build instructions

datahandling: 
	mpost datahandling2

modelsfig: 
	mpost models 

algorithm: 
	mpost EMalg 

all:
	mpost datahandling2
	mpost models
	mpost EMalg 
	pdflatex notes.tex

latex:
	pdflatex notes.tex
