var annotated_dup =
[
    [ "bounds", "structbounds.html", "structbounds" ],
    [ "classifier", "classclassifier.html", "classclassifier" ],
    [ "classifier_single", "classclassifier__single.html", "classclassifier__single" ],
    [ "component", "classcomponent.html", "classcomponent" ],
    [ "EMG", "class_e_m_g.html", "class_e_m_g" ],
    [ "exponential", "classexponential.html", "classexponential" ],
    [ "gap_interval", "classgap__interval.html", "classgap__interval" ],
    [ "Log_File", "class_log___file.html", "class_log___file" ],
    [ "NLR", "class_n_l_r.html", "class_n_l_r" ],
    [ "node", "classnode.html", "classnode" ],
    [ "NOISE", "class_n_o_i_s_e.html", "class_n_o_i_s_e" ],
    [ "normal", "classnormal.html", "classnormal" ],
    [ "NORMAL", "class_n_o_r_m_a_l.html", "class_n_o_r_m_a_l" ],
    [ "params", "classparams.html", "classparams" ],
    [ "ParamWrapper", "class_param_wrapper.html", "class_param_wrapper" ],
    [ "pareto", "classpareto.html", "classpareto" ],
    [ "segment", "classsegment.html", "classsegment" ],
    [ "segment_fits", "classsegment__fits.html", "classsegment__fits" ],
    [ "simple_c", "structsimple__c.html", "structsimple__c" ],
    [ "simple_c_free_mode", "structsimple__c__free__mode.html", "structsimple__c__free__mode" ],
    [ "simple_seg_struct", "structsimple__seg__struct.html", "structsimple__seg__struct" ],
    [ "single_simple_c", "structsingle__simple__c.html", "structsingle__simple__c" ],
    [ "slice_ratio", "classslice__ratio.html", "classslice__ratio" ],
    [ "UNI", "class_u_n_i.html", "class_u_n_i" ]
];